insert into alternativa (QuesId, AltDesc, AltCorreta)
				 values (1,      'Clone.',      0),
						(1,      'Híbrida.',      0),
                        (1,      'Mutante.',      0),
                        (1,      'Dominante.',      0),
                        (1,      'Transgênica.',      1),
                        (2,      'fotossíntese.',      1),
                        (2,      'fermentação.',      0),
                        (2,      'quimiossíntese.',      0),
                        (2,      'hidrólise de ATP.',      0),
                        (2,      'respiração celular.',      0),
                        (3,      'Hipófise.',      0),
                        (3,      'Tireoide.',      1),
                        (3,      'Pâncreas.',      0),
                        (3,      'Suprarrenal.',      0),
                        (3,      'Paratireoide.',      0),
                        (4,      'direcionar as pilhas e baterias para compostagem.',      0),
                        (4,      'colocar as pilhas e baterias em um coletor de lixo seletivo.',      0),
                        (4,      'enviar as pilhas e baterias usadas para firmas de recarga.',      0),
                        (4,      'acumular as pilhas e baterias em armazéns de estocagem.',      0),
                        (4,      'destinar as pilhas e baterias à reutilização de seus componentes.',      1),
                        (5,      '19 L.',      0),
                        (5,      '39 L.',      0),
                        (5,      '71 L.',      1),
                        (5,      '97 L.',      0),
                        (5,      '141 L.',      0),
                        (6,      'aumento do ponto de ebulição do solvente.',      0),
                        (6,      'passagem do soluto através de uma membrana semipermeável.',      0),
                        (6,      'utilização de solutos voláteis, que facilitam a evaporação do solvente.',      0),
                        (6,      'aumento da volatilidade do solvente pela adição de solutos ao produto.',      0),
                        (6,      'pressão gerada pela diferença de concentração entre o produto e a solução.',      1),
                        (7,      'nitratação.',      1),
                        (7,      'nitrosação.',      0),
                        (7,      'amonificação.',      0),
                        (7,      'desnitrificação.',      0),
                        (7,      'fixação biológica do N2.',      0),
                        (8,      'reação do gás de cozinha com o sal, volatilizando gás cloro.',      0),
                        (8,      'emissão de fótons pelo sódio, excitado por causa da chama.',      1),
                        (8,      'produção de derivado amarelo, pela reação com o carboidrato.',      0),
                        (8,      'reação do gás de cozinha com a água, formando gás hidrogênio.',      0),
                        (8,      'excitação das moléculas de proteínas, com formação de luz amarela. ',      0),
                        (9,      '450. ',      0),
                        (9,      '1 433.',      0),
                        (9,      '11 460.',      1),
                        (9,      '17 190.',      0),
                        (9,      '27 000.',      0),
                        (10,      'das diferentes densidades.',      1),
                        (10,      'dos diferentes raios de rotação.',      0),
                        (10,      'das diferentes velocidades angulares.',      0),
                        (10,      'das diferentes quantidades de cada substância.',      0),
                        (10,      'da diferente coesão molecular de cada substância.',      0),
                        (11,      'voto secreto e candidatura em eleições.',      0),
                        (11,      'moradia digna e vagas em universidade.',      0),
                        (11,      'previdência social e saúde de qualidade.',      1),
                        (11,      'igualdade jurídica e liberdade de expressão.',      0),
                        (11,      'filiação partidária e participação em sindicatos.',      0),
                        (12,      'consolidação da historiografia oficial.',      0),
                        (12,      'definição do mercado cultural.',      0),
                        (12,      'afirmação da identidade nacional.',      1),
                        (12,      'divulgação de sítios arqueológicos.',      0),
                        (12,      'universalização de saberes museológicos. ',      0),
                        (13,      'carência de meios de transporte que permitissem uma rápida integração entre as áreas produtoras e consumidoras.',      0),
                        (13,      'produção nas plantações de seringueiras do sudeste asiático, que ocasionou um excesso da produção mundial.',      1),
                        (13,      'chamado encilhamento, que resultou na desvalorização da moeda brasileira após forte especulação na Bolsa de Valores.',      0),
                        (13,      'fim da migração de nordestinos para a Amazônia, que gerou uma enorme carência de mão de obra na região.',      0),
                        (13,      'início da Primeira Guerra Mundial, que paralisou o comércio internacional e provocou o declínio da economia brasileira. ',      0),
                        (14,      'conquista do sufrágio universal.',      0),
                        (14,      'criação do regime parlamentarista.',      0),
                        (14,      'institucionalização do voto feminino.',      0),
                        (14,      'decadência das monarquias hereditárias.',      0),
                        (14,      'consolidação da democracia representativa.',      1),
                        (15,      'imprensa escrita.',      1),
                        (15,      'oficialato militar. ',      0),
                        (15,      'corte palaciana. ',      0),
                        (15,      'clero católico. ',      0),
                        (15,      'câmara de representantes.',      0),
                        (16,      'direito de voto.',      1),
                        (16,      'garantia de cotas.',      0),
                        (16,      'acesso ao trabalho.',      0),
                        (16,      'organização partidária.',      0),
                        (16,      'igualdade de oportunidades.',      0),
                        (17,      'aprovação de medidas de inclusão social.',      0),
                        (17,      'adoção de crianças com diferentes características físicas.',      0),
                        (17,      'estabelecimento de legislação que combatia as divisões sociais.',      0),
                        (17,      'prisão e esterilização de pessoas com características consideradas inferiores.',      1),
                        (17,      'desenvolvimento de próteses que possibilitavam a reabilitação de pessoas deficientes. ',      0),
                        (18,      'exaltar o modelo absolutista e despótico.',      0),
                        (18,      'valorizar a mestiçagem africana e nativa.',      0),
                        (18,      'reduzir a participação democrática e popular.',      0),
                        (18,      'mobilizar o sentimento patriótico e antilusitano.',      0),
                        (18,      'obscurecer a origem portuguesa e colonizadora.',      1),
                        (19,      'criação da Justiça Eleitoral. ',      0),
                        (19,      'exigência da alfabetização.',      1),
                        (19,      'redução da renda nacional.',      0),
                        (19,      'exclusão do voto feminino.',      0),
                        (19,      'coibição do voto de cabresto.',      0),
                        (20,      'samba exaltação.',      1),
                        (20,      'música de sátira.',      0),
                        (20,      'hino revolucionário.',      0),
                        (20,      'propaganda eleitoral.',      0),
                        (20,      'marchinha de protesto.',      0),
                        (21,      'estética facial.',      0),
                        (21,      'mímica corporal.',      1),
                        (21,      'amarra no corpo.',      0),
                        (21,      'função da máscara. ',      0),
                        (21,      'simbologia do tecido.',      0),
                        (22,      'criar fatos com a imaginação.',      0),
                        (22,      'reproduzir as notícias dos jornais.',      0),
                        (22,      'escrever em linguagem coloquial.',      0),
                        (22,      'construir personagens verossímeis.',      0),
                        (22,      'ressignificar o cotidiano pela escrita.',      1),
                        (23,      'reflexão da sociedade sobre os produtos anunciados. ',      0),
                        (23,      'difusão do pensamento e das preferências das grandes massas. ',      0),
                        (23,      'imposição das idéias e posições de grupos específicos.',      1),
                        (23,      'decisão consciente do consumidor a respeito de sua compra.',      0),
                        (23,      'identificação dos interesses do responsável pelo produto divulgado.',      0),
                        (24,      'trechos de cantigas.',      0),
                        (24,      'rituais de mandingas.',      0),
                        (24,      'citações de preceitos.',      0),
                        (24,      'cerimônias religiosas.',      0),
                        (24,      'exemplos de superstições.',      1),
                        (25,      'judô e karatê.',      1),
                        (25,      'jiu-jítsu e sumô.',      0),
                        (25,      'boxe e kung fu.',      0),
                        (25,      'esgrima e luta olímpica.',      0),
                        (25,      'Muay Thai e tae kwon do.',      0),
                        (26,      'referir-se ao fato de a decisão judicial não implicar a sua imediata aplicação.',      0),
                        (26,      'destacar a inevitável execução da sentença.',      0),
                        (26,      'ironizar a parcialidade da Justiça nessa ação.',      1),
                        (26,      'criticar a coleta compulsória do material genético.',      0),
                        (26,      'enfatizar a determinação judicial como algo consolidado. ',      0),
                        (27,      'denunciar as práticas que encobrem as diferenças.',      0),
                        (27,      'tornar públicas as razões econômicas da xenofobia.',      0),
                        (27,      'criticar aqueles que favorecem a aparição do medo.',      1),
                        (27,      'reclamar das atitudes tomadas pelos países desenvolvidos.',      0),
                        (27,      'apontar as causas que determinam os fluxos migratórios.',      0),
                        (28,      'O mais forte sempre vence.',      0),
                        (28,      'A união faz a força.',      1),
                        (28,      'A força carrega a justiça nas costas.',      0),
                        (28,      'O ataque é a melhor defesa.',      0),
                        (28,      'O inimigo da vida é a morte.',      0),
                        (29,      'foi objeto de novelas televisivas baseadas em sua vida noturna e artística.',      0),
                        (29,      'manteve sua elegância e espírito cosmopolita, apesar das crises econômicas.',      1),
                        (29,      'teve sua energia e aspecto empreendedor ofuscados pela incerteza da economia.',      0),
                        (29,      'foi marcada historicamente por uma vida financeira estável, com repercussão na arte.',      0),
                        (29,      'parou de atrair apreciadores da gastronomia, devido ao alto valor de sua moeda.',      0),
                        (30,      'emprego no setor imobiliário.',      0),
                        (30,      'imóvel residencial para compra.',      1),
                        (30,      'serviço de reparos em domicílio.',      0),
                        (30,      'pessoa para trabalho doméstico.',      0),
                        (30,      'curso de decorador de interiores.',      0),
                        (31,      '11 200.',      1),
                        (31,      '1 120.	',      0),
                        (31,      '112.',      0),
                        (31,      '11,2.',      0),
                        (31,      '1,12.',      0),
                        (32,      '1/3',      0),
                        (32,      '1/18',      0),
                        (32,      '1/40',      0),
                        (32,      '1/54',      1),
                        (32,      '7/18',      0),
                        (33,      '10,80 km/L',      0),
                        (33,      '12,65 km/L',      0),
                        (33,      '12,82 km/L',      0),
                        (33,      '14,15 km/L ',      0),
                        (33,      '14,40 km/L',      1),
                        (34,      '18',      0),
                        (34,      '20',      0),
                        (34,      '31',      0),
                        (34,      '50',      1),
                        (34,      '62',      0),
                        (35,      '2. ',      0),
                        (35,      '4. ',      0),
                        (35,      '6. ',      0),
                        (35,      '8. ',      0),
                        (35,      '9.',      1),
                        (36,      '144.',      1),
                        (36,      '225.',      0),
                        (36,      '3 600.',      0),
                        (36,      '7 500.',      0),
                        (36,      '32 400.',      0),
                        (37,      'ganhou 6,5% em poder aquisitivo de carne. ',      0),
                        (37,      'ganhou 7% em poder aquisitivo de carne. ',      0),
                        (37,      'ganhou 7,5% em poder aquisitivo de carne. ',      1),
                        (37,      'perdeu 7% em poder aquisitivo de carne.',      0),
                        (37,      'perdeu 7,5% em poder aquisitivo de carne.',      0),
                        (38,      '200.',      0),
                        (38,      '209.',      0),
                        (38,      '270.',      1),
                        (38,      '340.',      0),
                        (38,      '475.',      0),
                        (39,      '0.',      1),
                        (39,      '2. ',      0),
                        (39,      '4.',      0),
                        (39,      '6. ',      0),
                        (39,      '8.',      0),
                        (40,      '90',      0),
                        (40,      '100',      1),
                        (40,      '125	',      0),
                        (40,      '195',      0),
                        (40,      '200',      0)
                        
