CREATE DATABASE IF NOT EXISTS `tcc_engsoft` ;
USE `tcc_engsoft`;

CREATE TABLE alternativa (
  AltId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  QuesId INTEGER UNSIGNED NOT NULL,
  AltDesc VARCHAR(512) NULL,
  AltCorreta INTEGER UNSIGNED NULL,
  PRIMARY KEY(AltId),
  INDEX alternativa_FKIndex1(QuesId)
);

CREATE TABLE area_conhecimento (
  AreaId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AreaNome VARCHAR(50) NULL,
  PRIMARY KEY(AreaId)
);

CREATE TABLE avaliacao (
  AvaId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  UsuId INTEGER UNSIGNED NOT NULL,
  AvaNota DOUBLE NULL,
  AvaMsg VARCHAR(1024) NULL,
  AvaData DATETIME NULL,
  PRIMARY KEY(AvaId),
  INDEX avaliacao_FKIndex1(UsuId)
);

CREATE TABLE cidade (
  CidId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  EstId INTEGER UNSIGNED NOT NULL,
  CidNome VARCHAR(50) NULL,
  PRIMARY KEY(CidId),
  INDEX cidade_FKIndex1(EstId)
);

CREATE TABLE conquista (
  ConId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ConConfId INTEGER UNSIGNED NOT NULL,
  UsuId INTEGER UNSIGNED NOT NULL,
  ConData DATETIME NULL,
  PRIMARY KEY(ConId),
  INDEX conquista_FKIndex1(UsuId),
  INDEX conquista_FKIndex2(ConConfId)
);

CREATE TABLE conquista_config (
  ConConfId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ConConfTitulo INTEGER UNSIGNED NULL,
  ConConfDesc VARCHAR(255) NULL,
  PRIMARY KEY(ConConfId)
);

CREATE TABLE curso (
  CurId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CurNome VARCHAR(50) NULL,
  CurDataCad DATETIME NULL,
  PRIMARY KEY(CurId)
);

CREATE TABLE estado (
  EstId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  EstNome VARCHAR(40) NULL,
  EstUf VARCHAR(2) NULL,
  PRIMARY KEY(EstId)
);

CREATE TABLE questao (
  QuesId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AreaId INTEGER UNSIGNED NOT NULL,
  QuesDesc VARCHAR(1024) NULL,
  QuesAtiva INTEGER UNSIGNED NULL,
  QuesDataCad DATETIME NULL,
  PRIMARY KEY(QuesId),
  INDEX questao_FKIndex1(AreaId)
);

CREATE TABLE resposta (
  ResId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  AltId INTEGER UNSIGNED NOT NULL,
  UsuId INTEGER UNSIGNED NOT NULL,
  ResPontos DOUBLE NULL,
  ResData DATETIME NULL,
  PRIMARY KEY(ResId),
  INDEX resposta_FKIndex1(UsuId),
  INDEX resposta_FKIndex2(AltId)
);

CREATE TABLE universidade (
  UniId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CidId INTEGER UNSIGNED NOT NULL,
  UniNome VARCHAR(100) NULL,
  UniDataCad DATETIME NULL,
  PRIMARY KEY(UniId),
  INDEX universidade_FKIndex1(CidId)
);

CREATE TABLE universidade_curso (
  UniCurId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CurId INTEGER UNSIGNED NOT NULL,
  UniId INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(UniCurId),
  INDEX universidade_curso_FKIndex1(UniId),
  INDEX universidade_curso_FKIndex2(CurId)
);

CREATE TABLE usuario (
  UsuId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CurId INTEGER UNSIGNED NOT NULL,
  UniId INTEGER UNSIGNED NOT NULL,
  CidId INTEGER UNSIGNED NOT NULL,
  UsuNome VARCHAR(80) NULL,
  UsuEmail VARCHAR(40) NULL,
  UsuSenha VARCHAR(50) NULL,
  UsuDireito VARCHAR(15) NULL,
  UsuAtivo INTEGER UNSIGNED NULL,
  UsuFoto VARCHAR(255) NULL,
  UsuDataNasc DATE NULL,
  UsuDataCad DATETIME NULL,
  UsuAudio INTEGER UNSIGNED NULL,
  PRIMARY KEY(UsuId),
  INDEX usuario_FKIndex1(CidId),
  INDEX usuario_FKIndex2(UniId),
  INDEX usuario_FKIndex3(CurId)
);

